### PR TITLE
fix IF EXISTS in ALTER TABLE IF EXISTS

### PR DESCRIPTION
**Pull request by jmo-qap**
Adds a new test case for `ALTER TABLE IF EXISTS told RENAME cold TO cnew` and adds appropriate fix

### CODE REVIEW

**Comment by lelit** [comment]
Thank you. Can you try to narrow the patch to essential, removing other "automatic" and extraneous changes?

**Comment by jmo-qap** [comment]
Done

**Comment by lelit** [comment]
Great, will merge as time permits, thanks again!

**Comment by jmo-qap** [comment]
Turns out the initial version was incomplete and a bit too general. Looking through https://www.postgresql.org/docs/12/sql-commands.html the only place I could find `IF EXISTS` for a rename is after an `ALTER TABLE` so I've limited it to that scope. I also added an `else` to make the flow a bit clearer.

**Comment by jmo-qap** [comment]
And added `Views`

**Comment by lelit** [comment]
Thank you Jonathan, hope to release v1.15 this weekend.

**Pull request merged**
