### PR TITLE
Add node_print for RuleStmt

### PR DESCRIPTION
**Pull request by gmr**
Not quite sure how you would have wanted to format it, but I tried to match what I saw of other printers.

### CODE REVIEW

**Comment by lelit** [comment]
Ideally this should use symbolic constant, instead of those hardcoded 1,2,3.

I will have a better look as soon as I can.

**Comment by gmr** [comment]
Better?

**Comment by lelit** [comment]
The (manual) addition to parsenodes.py is not needed, and in general *wrong*: the modules under `enums` are created automatically from the PostgreSQL include files, so if anything is missing, its the extractor (`tools/extract_enums.py`) that would need a fix, otherwise next regeneration will clobber the manual tweak.

The specific values for the `event` field are defined in `nodes.CmdType`, could you rectify and use those enums instead?

Thanks!

**Comment by lelit** [comment]
I've reimplemented the printer, properly handling the full syntax.
Thank you for the initial proposal, and sorry for taking so long!

**Pull request closed without merging**
